#APP CONFIG

app.base-url=http://localhost:8080/uploads
spring.application.name=catalog
#spring.h2.console.enabled=true

#Meta
app.name=catalog
app.version=0.0.1
app.author=Josec
app.language=es
app.country=Spain

#CONEXIÓN CON LA BASE DE DATOS
# 1. Dirección de la base de datos (puerto 5432 y nombre catalog_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/catalog_db

# 2. Credenciales que creaste en la instalación
spring.datasource.username=postgres
spring.datasource.password=6tTX49t2CXh1

# 3. El dialecto que debe usar JPA para traducir el código a SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. ¡LA MAGIA DE SPRING!
# 'update' le dice a Spring: "Si las tablas no existen, créalas automáticamente leyendo las clases @Entity. Si existen, actualízalas".
spring.jpa.hibernate.ddl-auto=update

# 5. Opcional: Mostrar el SQL en la consola (útil para ver qué hace Spring por debajo)
spring.jpa.show-sql=true


#DEGUB
#Chivato de spring security
logging.level.org.springframework.security=TRACE